DefChecker.exe test\\f1.c
DefChecker.exe test\\f2.c
DefChecker.exe test\\f3.c
DefChecker.exe test\\f4.c
DefChecker.exe test\\f5.c
DefChecker.exe test\\f6.c
DefChecker.exe test\\instructions.c
DefChecker.exe test\\instructions_1.c
DefChecker.exe test\\instructions_2.c
DefChecker.exe test\\instructions_3.c
DefChecker.exe test\\ifelse.c
DefChecker.exe test\\nested_ifelse.c
DefChecker.exe test\\nested_if.c
DefChecker.exe test\\nested_if_noelse.c
DefChecker.exe test\\multi_assign.c
DefChecker.exe test\\multi_assign_expr.c
DefChecker.exe test\\while_break.c
DefChecker.exe test\\while_continue.c
DefChecker.exe test\\for_break.c
DefChecker.exe test\\for_continue.c
DefChecker.exe test\\forLoop.c
DefChecker.exe test\\forLoop_1.c
DefChecker.exe test\\return.c
DefChecker.exe test\\return_if.c
DefChecker.exe test\\pointers_1.c
DefChecker.exe test\\pointers_2.c
DefChecker.exe test\\pointers_3.c
DefChecker.exe test\\pointers_4.c
DefChecker.exe test\\functionPointer_1.c
DefChecker.exe test\\functionPointer_2.c
DefChecker.exe test\\functionPointer_3.c
DefChecker.exe test\\functionPointer_4.c
DefChecker.exe test\\array_1.c
DefChecker.exe test\\array_2.c
DefChecker.exe test\\array_3.c
DefChecker.exe test\\struct_1.c
DefChecker.exe test\\struct_2.c
DefChecker.exe test\\struct_3.c
DefChecker.exe test\\ampersandOperator.c
DefChecker.exe test\\malloc.c
DefChecker.exe test\\delete.c
DefChecker.exe test\\mem_1.c
DefChecker.exe test\\mem_2.c
DefChecker.exe test\\swap_num.c