set outputPath=%1
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\f1.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\f2.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\f3.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\f4.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\f5.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\f6.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\instructions.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\instructions_1.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\instructions_2.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\instructions_3.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\ifelse.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\nested_ifelse.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\nested_if.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\nested_if_noelse.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\multi_assign.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\multi_assign_expr.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\while_break.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\while_continue.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\for_break.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\for_continue.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\forLoop.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\forLoop_1.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\return.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\return_if.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\pointers_1.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\pointers_2.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\pointers_3.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\pointers_4.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\functionPointer_1.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\functionPointer_2.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\functionPointer_3.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\functionPointer_4.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\array_1.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\array_2.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\array_3.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\struct_1.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\struct_2.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\struct_3.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\ampersandOperator.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\malloc.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\free.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\mem_1.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\mem_2.c -o %outputPath%
DefChecker.exe -i C:\workspace\my_repo\sca\\test\\swap_num.c -o %outputPath%